// Generated by tests/make_avatar_fixture.mjs from ather-automata/hooks/squad.mjs avatarSvg; do not edit by hand.
export const AVATARS: { kind: string; prop: string | null; state: string; source: string }[] = [
  {
    "kind": "editor",
    "prop": null,
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><rect x=\"28\" y=\"30\" width=\"44\" height=\"96\" rx=\"22\" fill=\"#f08a3c\"/><rect x=\"39\" y=\"45\" width=\"6\" height=\"14\" rx=\"3\" fill=\"#1b1b1b\"/><rect x=\"55\" y=\"45\" width=\"6\" height=\"14\" rx=\"3\" fill=\"#1b1b1b\"/></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "editor",
    "prop": "reading",
    "state": "done",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><rect x=\"28\" y=\"30\" width=\"44\" height=\"96\" rx=\"22\" fill=\"#f08a3c\"/><rect x=\"39\" y=\"45\" width=\"6\" height=\"14\" rx=\"3\" fill=\"#1b1b1b\"/><rect x=\"55\" y=\"45\" width=\"6\" height=\"14\" rx=\"3\" fill=\"#1b1b1b\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(55 70) rotate(-10)\"><rect width=\"32\" height=\"24\" rx=\"2\" fill=\"#f1ede2\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><rect x=\"4\" y=\"4\" width=\"9\" height=\"8\" fill=\"#8d8d86\"/><path d=\"M16 5h12M16 9h12M4 15h24M4 19h24\" stroke=\"#8d8d86\" stroke-width=\"2\"/></g></g></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#3ccf7a\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "editor",
    "prop": "editing",
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><rect x=\"28\" y=\"30\" width=\"44\" height=\"96\" rx=\"22\" fill=\"#f08a3c\"/><rect x=\"39\" y=\"45\" width=\"6\" height=\"14\" rx=\"3\" fill=\"#1b1b1b\"/><rect x=\"55\" y=\"45\" width=\"6\" height=\"14\" rx=\"3\" fill=\"#1b1b1b\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(57 66) rotate(-8)\"><rect width=\"23\" height=\"28\" rx=\"2\" fill=\"#4b1f5c\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#111\" stroke-width=\"7\" stroke-linecap=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#e8b21c\" stroke-width=\"4.5\" stroke-linecap=\"round\"/></g></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "builder",
    "prop": null,
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><rect x=\"19\" y=\"44\" width=\"62\" height=\"74\" rx=\"17\" fill=\"#2f8cf0\" transform=\"rotate(-8 50 76)\"/><ellipse cx=\"39\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/><ellipse cx=\"58\" cy=\"61\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "builder",
    "prop": "reading",
    "state": "done",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><rect x=\"19\" y=\"44\" width=\"62\" height=\"74\" rx=\"17\" fill=\"#2f8cf0\" transform=\"rotate(-8 50 76)\"/><ellipse cx=\"39\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/><ellipse cx=\"58\" cy=\"61\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(55 70) rotate(-10)\"><rect width=\"32\" height=\"24\" rx=\"2\" fill=\"#f1ede2\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><rect x=\"4\" y=\"4\" width=\"9\" height=\"8\" fill=\"#8d8d86\"/><path d=\"M16 5h12M16 9h12M4 15h24M4 19h24\" stroke=\"#8d8d86\" stroke-width=\"2\"/></g></g></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#3ccf7a\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "builder",
    "prop": "editing",
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><rect x=\"19\" y=\"44\" width=\"62\" height=\"74\" rx=\"17\" fill=\"#2f8cf0\" transform=\"rotate(-8 50 76)\"/><ellipse cx=\"39\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/><ellipse cx=\"58\" cy=\"61\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(57 66) rotate(-8)\"><rect width=\"23\" height=\"28\" rx=\"2\" fill=\"#4b1f5c\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#111\" stroke-width=\"7\" stroke-linecap=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#e8b21c\" stroke-width=\"4.5\" stroke-linecap=\"round\"/></g></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "tester",
    "prop": null,
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><path d=\"M50 50 L57.6 69.5 L78.5 70.7 L62.4 84 L67.6 104.3 L50 93 L32.4 104.3 L37.6 84 L21.5 70.7 L42.4 69.5 Z\" fill=\"#2fbfa8\" stroke=\"#2fbfa8\" stroke-width=\"10\" stroke-linejoin=\"round\"/><ellipse cx=\"44.5\" cy=\"77\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"55.5\" cy=\"77\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "tester",
    "prop": "reading",
    "state": "done",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><path d=\"M50 50 L57.6 69.5 L78.5 70.7 L62.4 84 L67.6 104.3 L50 93 L32.4 104.3 L37.6 84 L21.5 70.7 L42.4 69.5 Z\" fill=\"#2fbfa8\" stroke=\"#2fbfa8\" stroke-width=\"10\" stroke-linejoin=\"round\"/><ellipse cx=\"44.5\" cy=\"77\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"55.5\" cy=\"77\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(55 70) rotate(-10)\"><rect width=\"32\" height=\"24\" rx=\"2\" fill=\"#f1ede2\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><rect x=\"4\" y=\"4\" width=\"9\" height=\"8\" fill=\"#8d8d86\"/><path d=\"M16 5h12M16 9h12M4 15h24M4 19h24\" stroke=\"#8d8d86\" stroke-width=\"2\"/></g></g></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#3ccf7a\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "tester",
    "prop": "editing",
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><path d=\"M50 50 L57.6 69.5 L78.5 70.7 L62.4 84 L67.6 104.3 L50 93 L32.4 104.3 L37.6 84 L21.5 70.7 L42.4 69.5 Z\" fill=\"#2fbfa8\" stroke=\"#2fbfa8\" stroke-width=\"10\" stroke-linejoin=\"round\"/><ellipse cx=\"44.5\" cy=\"77\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"55.5\" cy=\"77\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(57 66) rotate(-8)\"><rect width=\"23\" height=\"28\" rx=\"2\" fill=\"#4b1f5c\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#111\" stroke-width=\"7\" stroke-linecap=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#e8b21c\" stroke-width=\"4.5\" stroke-linecap=\"round\"/></g></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "scout",
    "prop": null,
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><g fill=\"#c9b3ee\"><circle cx=\"32\" cy=\"72\" r=\"18\"/><circle cx=\"50\" cy=\"60\" r=\"21\"/><circle cx=\"68\" cy=\"72\" r=\"18\"/><rect x=\"18\" y=\"72\" width=\"64\" height=\"44\" rx=\"14\"/></g><ellipse cx=\"42\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"59\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "scout",
    "prop": "reading",
    "state": "done",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><g fill=\"#c9b3ee\"><circle cx=\"32\" cy=\"72\" r=\"18\"/><circle cx=\"50\" cy=\"60\" r=\"21\"/><circle cx=\"68\" cy=\"72\" r=\"18\"/><rect x=\"18\" y=\"72\" width=\"64\" height=\"44\" rx=\"14\"/></g><ellipse cx=\"42\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"59\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(55 70) rotate(-10)\"><rect width=\"32\" height=\"24\" rx=\"2\" fill=\"#f1ede2\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><rect x=\"4\" y=\"4\" width=\"9\" height=\"8\" fill=\"#8d8d86\"/><path d=\"M16 5h12M16 9h12M4 15h24M4 19h24\" stroke=\"#8d8d86\" stroke-width=\"2\"/></g></g></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#3ccf7a\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "scout",
    "prop": "editing",
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><g fill=\"#c9b3ee\"><circle cx=\"32\" cy=\"72\" r=\"18\"/><circle cx=\"50\" cy=\"60\" r=\"21\"/><circle cx=\"68\" cy=\"72\" r=\"18\"/><rect x=\"18\" y=\"72\" width=\"64\" height=\"44\" rx=\"14\"/></g><ellipse cx=\"42\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"59\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(57 66) rotate(-8)\"><rect width=\"23\" height=\"28\" rx=\"2\" fill=\"#4b1f5c\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#111\" stroke-width=\"7\" stroke-linecap=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#e8b21c\" stroke-width=\"4.5\" stroke-linecap=\"round\"/></g></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "reviewer",
    "prop": null,
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><defs><mask id=\"moon\"><rect width=\"100\" height=\"130\" fill=\"#fff\"/><circle cx=\"80\" cy=\"62\" r=\"29\" fill=\"#000\"/></mask></defs><circle cx=\"50\" cy=\"86\" r=\"42\" fill=\"#f2d27a\" mask=\"url(#moon)\"/><ellipse cx=\"28\" cy=\"76\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"41\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "reviewer",
    "prop": "reading",
    "state": "done",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><defs><mask id=\"moon\"><rect width=\"100\" height=\"130\" fill=\"#fff\"/><circle cx=\"80\" cy=\"62\" r=\"29\" fill=\"#000\"/></mask></defs><circle cx=\"50\" cy=\"86\" r=\"42\" fill=\"#f2d27a\" mask=\"url(#moon)\"/><ellipse cx=\"28\" cy=\"76\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"41\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(55 70) rotate(-10)\"><rect width=\"32\" height=\"24\" rx=\"2\" fill=\"#f1ede2\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><rect x=\"4\" y=\"4\" width=\"9\" height=\"8\" fill=\"#8d8d86\"/><path d=\"M16 5h12M16 9h12M4 15h24M4 19h24\" stroke=\"#8d8d86\" stroke-width=\"2\"/></g></g></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#3ccf7a\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "reviewer",
    "prop": "editing",
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><defs><mask id=\"moon\"><rect width=\"100\" height=\"130\" fill=\"#fff\"/><circle cx=\"80\" cy=\"62\" r=\"29\" fill=\"#000\"/></mask></defs><circle cx=\"50\" cy=\"86\" r=\"42\" fill=\"#f2d27a\" mask=\"url(#moon)\"/><ellipse cx=\"28\" cy=\"76\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/><ellipse cx=\"41\" cy=\"74\" rx=\"4.6\" ry=\"6\" fill=\"#1b1b1b\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(57 66) rotate(-8)\"><rect width=\"23\" height=\"28\" rx=\"2\" fill=\"#4b1f5c\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#111\" stroke-width=\"7\" stroke-linecap=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#e8b21c\" stroke-width=\"4.5\" stroke-linecap=\"round\"/></g></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "general",
    "prop": null,
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><ellipse cx=\"50\" cy=\"88\" rx=\"36\" ry=\"46\" fill=\"#ec5fa4\"/><ellipse cx=\"40\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/><ellipse cx=\"59\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "general",
    "prop": "reading",
    "state": "done",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><ellipse cx=\"50\" cy=\"88\" rx=\"36\" ry=\"46\" fill=\"#ec5fa4\"/><ellipse cx=\"40\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/><ellipse cx=\"59\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(55 70) rotate(-10)\"><rect width=\"32\" height=\"24\" rx=\"2\" fill=\"#f1ede2\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><rect x=\"4\" y=\"4\" width=\"9\" height=\"8\" fill=\"#8d8d86\"/><path d=\"M16 5h12M16 9h12M4 15h24M4 19h24\" stroke=\"#8d8d86\" stroke-width=\"2\"/></g></g></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#3ccf7a\" stroke-width=\"6\"/></svg>"
  },
  {
    "kind": "general",
    "prop": "editing",
    "state": "running",
    "source": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" style=\"color-scheme: light dark; background: transparent\"><defs><clipPath id=\"round\"><circle cx=\"50\" cy=\"50\" r=\"43\"/></clipPath></defs><circle cx=\"50\" cy=\"50\" r=\"43\" fill=\"#17181a\"/><g clip-path=\"url(#round)\"><g><g transform=\"translate(50 106) scale(1.32) translate(-50 -106)\"><ellipse cx=\"50\" cy=\"88\" rx=\"36\" ry=\"46\" fill=\"#ec5fa4\"/><ellipse cx=\"40\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/><ellipse cx=\"59\" cy=\"64\" rx=\"4.6\" ry=\"6\" fill=\"#f6f0e0\"/></g><g transform=\"translate(67 75) scale(1.22) translate(-70 -82)\"><g transform=\"translate(57 66) rotate(-8)\"><rect width=\"23\" height=\"28\" rx=\"2\" fill=\"#4b1f5c\" stroke=\"#111\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#111\" stroke-width=\"7\" stroke-linecap=\"round\"/><path d=\"M12 32 L34 4\" stroke=\"#e8b21c\" stroke-width=\"4.5\" stroke-linecap=\"round\"/></g></g><animateTransform attributeName=\"transform\" type=\"translate\" values=\"0 0;0 -2.5;0 0\" dur=\"1.8s\" repeatCount=\"indefinite\"/></g></g><circle cx=\"50\" cy=\"50\" r=\"45.5\" fill=\"none\" stroke=\"#ddff00\" stroke-width=\"6\"/></svg>"
  }
]
