// Regenerates tests/svg-calls.fixture.ts: every place a5's hooks build an `Svg` element (`Svg(` / `svg(` calls), with
// the line, its source expression and whether it can be interactive, so tests/frames.test.ts (A43) notices a new call
// site. The test runner cannot read the hooks' source itself. Run from the repository root:
//   node a5/tests/make_svg_calls_fixture.mjs
import fs from 'node:fs'

const dir = new URL('../hooks/', import.meta.url)
const calls = []
for (const file of fs.readdirSync(dir).filter(f => f.endsWith('.ts')).sort()) {
  const lines = fs.readFileSync(new URL(file, dir), 'utf8').split(/\r?\n/)
  lines.forEach((line, i) => {
    const t = line.trim()
    if (t.startsWith('//') || t.startsWith('*')) return
    const m = /\b(?:el\.Svg|svg)\(\{\s*source(?::\s*(.+?))?,\s*alt:/.exec(line)
    if (!m) return
    calls.push({ file, line: i + 1, source: (m[1] ?? 'source').trim(), isInteractive: /isInteractive/.test(line) })
  })
}
const out = `// Generated by tests/make_svg_calls_fixture.mjs from a5/hooks/*.ts; do not edit by hand.
export const SVG_CALLS: { file: string; line: number; source: string; isInteractive: boolean }[] = ${JSON.stringify(calls, null, 2)}
`
fs.writeFileSync(new URL('./svg-calls.fixture.ts', import.meta.url), out)
console.log(`svg-calls.fixture.ts: ${calls.length} Svg calls`)
