// Generated by tests/make_svg_calls_fixture.mjs from a5/hooks/*.ts; do not edit by hand.
export const SVG_CALLS: { file: string; line: number; source: string; isInteractive: boolean }[] = [
  {
    "file": "icons.ts",
    "line": 80,
    "source": "pixelSvg(ICONS[name], color, motion)",
    "isInteractive": true
  },
  {
    "file": "register.ts",
    "line": 1904,
    "source": "sealSvg(A5_LOOK.sealBg, A5_LOOK.sealText, true)",
    "isInteractive": true
  },
  {
    "file": "register.ts",
    "line": 1920,
    "source": "source",
    "isInteractive": true
  },
  {
    "file": "theme.ts",
    "line": 194,
    "source": "`${svgOpen('viewBox=\"0 0 10 10\"')}<title>${title}</title><circle cx=\"5\" cy=\"5\" r=\"2.2\" fill=\"${V2.label}\"/></svg>`",
    "isInteractive": true
  }
]
