// Regenerates tests/avatars.fixture.ts from Ather's own avatar drawing (ather-automata/hooks/squad.mjs), so the scarf
// tests (A39) read the avatars exactly as Ather ships them: the test runner cannot import outside the a5r folder.
// Run from the repository root: node a5r/tests/make_avatar_fixture.mjs
import fs from 'node:fs'
import { KINDS, avatarSvg } from '../../ather-automata/hooks/squad.mjs'

const rows = []
for (const kind of Object.keys(KINDS))
  for (const [prop, state] of [[null, 'running'], ['reading', 'done'], ['editing', 'running']]) rows.push({ kind, prop, state, source: avatarSvg(kind, prop, state) })
const out = `// Generated by tests/make_avatar_fixture.mjs from ather-automata/hooks/squad.mjs avatarSvg; do not edit by hand.
export const AVATARS: { kind: string; prop: string | null; state: string; source: string }[] = ${JSON.stringify(rows, null, 2)}
`
fs.writeFileSync(new URL('./avatars.fixture.ts', import.meta.url), out)
console.log(`avatars.fixture.ts: ${rows.length} avatars`)
