// Dev only: draws the original mod's SVG artwork (the Ather mark, the worker avatars and their
// props) to PNG, because Paseo plugins cannot render SVG. Writes server/art.generated.ts; the
// server hands the images to the app as data URIs. Run after changing squad.mjs or the mark:
//   npm run art
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";
import { KINDS, avatarSvg, propSvg } from "../ather/squad.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const png = (svg, width) => new Resvg(svg, { fitTo: { mode: "width", value: width }, background: "rgba(0,0,0,0)" }).render().asPng().toString("base64");

// The Ather mark from console.mjs: the A, its lime I, and the 5 raised as a power. The light
// version darkens both so they hold on a white page.
const mark = (a, lime) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 100"><polygon points="6,98 40,14 60,14 94,98 76,98 50,36 24,98" fill="${a}"/><rect x="47.5" y="56" width="5" height="28" fill="${lime}"/><text x="86" y="40" font-family="Arial Black, Arial, sans-serif" font-weight="900" font-size="40" fill="${lime}">5</text></svg>`;

const PROPS = ["reading", "editing", "building", "testing", "editor", "reviewing", "profiling", "idle"];
// The app draws the state ring and the running bob itself, so the avatar is the badge alone.
const badge = (kind, prop) =>
  avatarSvg(kind, prop, "waiting")
    .replace(/<animateTransform[^>]*\/>/g, "")
    .replace(/<circle cx="50" cy="50" r="45\.5"[^>]*\/>/, "");

const avatars = {};
for (const kind of Object.keys(KINDS)) {
  avatars[`${kind}:none`] = png(badge(kind, null), 112);
  for (const prop of PROPS) avatars[`${kind}:${prop}`] = png(badge(kind, prop), 112);
}
const props = Object.fromEntries(PROPS.map((prop) => [prop, png(propSvg(prop), 40)]));
const art = { logo: { dark: png(mark("#C9CCCC", "#DDFF00"), 144), light: png(mark("#3A3D3D", "#6E8A00"), 144) }, avatars, props };

const body = `// Generated by server/art/render.mjs from the original SVG artwork; do not edit.\nexport const ART: { logo: { dark: string; light: string }; avatars: Record<string, string>; props: Record<string, string> } = ${JSON.stringify(art)};\n`;
fs.writeFileSync(path.join(here, "..", "art.generated.ts"), body);
console.log(`wrote ${Object.keys(avatars).length} avatars, ${PROPS.length} props, 2 marks: ${(body.length / 1024).toFixed(0)} KB`);
