// Dev only: embeds the week-calendar scripts (../../week-calendar/scripts, the same ones the Claude Code
// plugin ships) into server/scripts.generated.ts, so the bundled server entry can copy them to
// ~/.calendar/bin (a stable path for the weekly scheduled task). Never edit the generated file.
//   npm run embed          regenerate it
//   npm run embed:check    fail if it is out of step with the scripts (dev/test-all.mjs runs this)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.resolve(here, "../../../week-calendar/scripts");
const target = path.join(here, "scripts.generated.ts");
// Line endings as committed, whatever the checkout's git settings did to them.
const read = (file) => fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n");

const files = {};
for (const name of ["build-calendar.mjs", "publish-report.mjs", "weekly.mjs", "schedule-weekly.mjs"]) files[name] = read(path.join(dir, name));
for (const name of fs.readdirSync(path.join(dir, "lib")).sort()) files[`lib/${name}`] = read(path.join(dir, "lib", name));
const body = `// Generated by server/embed.mjs from week-calendar/scripts; do not edit.\nexport const SCRIPTS: Record<string, string> = ${JSON.stringify(files, null, 1)};\n`;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== body) {
    console.error("paseo/week-calendar/server/scripts.generated.ts is out of step with week-calendar/scripts. Run npm run embed in paseo/week-calendar.");
    process.exit(1);
  }
  console.log("paseo/week-calendar: embedded scripts in step");
} else {
  fs.writeFileSync(target, body);
  console.log(`embedded ${Object.keys(files).length} files`);
}
